### ISSUE TITLE
[NEW] Elements / Dialogs / Banner

### ISSUE THREAD

**Issue by nicoleyeo** [artsy/palette#110]
## New Component: Banner

**Product team** Sell Team
**Design**   @nicoleyeo
**Eng** @jonallured 

[View zeplin link
](https://zpl.io/adkjxqp)
**Additional info**
Banners are used to convey time bound messages, statuses and specfic actions to our users. Depending on the timespan and importance of the message, they can either be a permanent part of the page, or can be dismissable. 

This build of the banner only includes the "error" state. In the future (when work is appropriately prioritized), we want to build upon this banner to include other states, such as: success, notification, warning.

**Context that initiates build**
We are building this to display a few errors in CMS when a gallery is managing orders (confirming, etc.)

**Comment by jonallured** [comment]
Closed with #114
