### ISSUE TITLE
Document SVG locations

### ISSUE THREAD

**Issue by jonallured** [artsy/palette#113]
At the design system sync meeting today we talked about opening an issue here on Palette to document locations where developers are dumping SVGs that we ultimately want to pull up into this project.

/cc @oxaudo

**Comment by jonallured** [comment]
Here are the places in Volt where we have SVGs:

```
app/assets/svgs
app/views/shared/svgs
app/javascript/shared/svgs
```

@anandaroop feel free to update this comment if there's another place I forgot! 😝

**Comment by anandaroop** [comment]
I think you covered it 😉 . The last path probably the most relevant in that it contains the newer design system / React versions.

**Comment by eessex** [comment]
There are a few spots for publishing -- 
https://github.com/artsy/reaction/tree/master/src/Components/Publishing/Icon

They are also scattered all throughout Positron, would be very happy to get these out and into a consolidated place: 
https://github.com/artsy/positron/search?l=SVG&q=svg

**Comment by oxaudo** [comment]
There are a lot of icons in Force:

src/desktop/components/main_layout/public/icons
src/desktop/components/bid_status/public/icons
src/desktop/apps/artsy_primer/templates
src/desktop/apps/artwork/components/partner_stub/public/icons
src/desktop/apps/editorial_features/components in several components there

src/mobile/public/images
src/mobile/apps/artwork/public/icons

**Comment by oxaudo** [comment]
There is also several places in Reaction

src/Assets
src/Assets/Icons
There are also some inline ones in different components.

**Comment by damassi** [comment]
Given resources its a bit of a stretch to revisit old backbone apps / old artsy design system icon code; however, all of our Reaction icons have since been moved to Palette, and things are in very good shape for all new work. Going to close!
