### ISSUE TITLE
Implement Sidebar Structure

### ISSUE THREAD

**Issue by owendodd** [artsy/palette#117]
As confirmed in #83 

---

**Home**
- About
- Change-log

---

**Tokens**
- Color
- Typography
- Spacing
- Grid
- Icons

---

**Elements**
- Images
  - Avatar
  - Image
  - ImageCarousel
  - LightBox
- Layout
  - BorderBox
  - Box
  - Flex
  - StackableBorderBox
  - Separator
  - Join
  - Overflow
  - ReadMore
- Buttons
  - Buttons
  - Text links
- Inputs
  - Input
  - QuickInput
  - Radio
  - GroupRadio
  - Checkbox
  - Dropdown
  - MiniDropdown
  - Slider
- Dialogs
  - Banner
  - Modal
  - Alert
  - Message
  - Confirmation
  - Tooltip
  - PopOver
- Navigation
  - Tabs
  - Pagination
- Animation
- Loaders
  - Spinner

---

**Components**
- Header
- Footer
- Bricks
  - ArtistBrick
  - GalleryBrick
  - ShowBrick
  - ArticleBrick
  - ArtworkBrick

**Comment by zephraph** [comment]
This is more or less finished? I'm going to close it for house keeping purposes. @owendodd let me know if we're missing anything.
