### ISSUE TITLE
[NEW] Element / Forms / Input

### ISSUE THREAD

**Issue by jeffreytr** [artsy/palette#253]
## Component Name
This is our standard input component used across the site. Will be following up with quick inputs and credit card inputs as separate components.

### Zeplin web
zpl.io/VkwJgkG
### Zeplin app
zpl://screen?pid=5acd19ff49a1429169c3128b&sid=5c54c42a8f59c8357d985948

### Product team

Discovery

### Team

@jeffreytr  @jonallured @pepopowitz 

---

#### For Tokens

_*Color, type, spacing, icons, etc*_

- [ ] Is it serving a purpose? (is it needed or just purely decorative?)

- [ ] Can it be merged with any existing styles on the site?

- [ ] Has it been pressure-tested in all instances?

- [ ] Does it meet accessibility standards? (min type size, color contrast)

#### For Elements

_*Buttons, links, loaders, inputs, dropdowns, etc*_

- [x] Is it using up-to-date tokens from above?

- [x] Have all states been captured? (hover, selected, disabled, focused, normal, thinking, errors)

- [x] Have all transitions/animations been defined?

- [x] Is it useable? (Considering touch targets, screen sizes)

- [x] Is it consistent with the rest of the visual system? (Corner radius, stroke weight, form, shadow, opacity, etc)

- [x] Does it meet accessibility standards? (is it keyboard navigable, does it have required accessibility markup)

- [x] Does it render and function properly in Artsy supported browsers?

#### For Components

_*Nav, modules, modals, cards, etc*_

- [x] Is it using up-to-date elements **and** tokens from above?

- [x] Does it communicate clearly? (Copy, writing style/tone)

- [x] Is it flexible? (Internationalization, text wrapping)

- [x] Is it logical from a UX perspective? Does it follow paradigms set on the rest of Artsy?

- [x] Has responsive behavior at all breakpoints been defined?

- [x] Have all transitions/animations been defined?

- [x] Does it meet accessibility standards?

- [x] Does it render and function properly in Artsy supported browsers?

#### Accessibility

- [ ] Do all images and multimedia have `alt` or `title` tags?

- [ ] Are semantic elements used appropriately (`nav`, `button`, etc)?

- [ ] Are new components keyboard-navigable?

- [ ] Are hover interactions available by other means?

- [ ] Are `aria-` attributes included where appropriate?

- [ ] Has a Chrome Devtools [accessibility audit](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#audits) been performed?

#### Compatibility

Has the new component been reviewed in [Browserstack](https://live.browserstack.com/dashboard):

- [ ] Desktop Chrome

- [ ] Desktop Edge

- [ ] Desktop Safari

- [ ] Desktop Firefox

- [ ] Android

- [ ] iOS

**Comment by jeffreytr** [comment]
@jonallured @pepopowitz This was added to Palette during the Search Results project right? Noticed there's still a WIP tag on it within Palette and was doing some cleanup on our workflow board. Can you confirm?

**Comment by samchieng** [comment]
Moved to Jira
https://artsyproduct.atlassian.net/browse/DSG-5
