### ISSUE TITLE
[QA] Palette Design QA 

### ISSUE THREAD

**Issue by nicoleyeo** [artsy/palette#279]
Looking amazing! Honestly mostly small things.

**UX / Bugs**
- [x] I feel like the UX of sidebar should be —  only 1 dropdown set should be allowed to be open at a time. If 1 dropdown option is open, and user clicks on a new item that is not in that drawer, the previously-open-dropdown should close. @owendodd @jeffreytr thoughts? Currently feeling like the sidebar gets crazy long if we let all of them be open. 

- [x] Would be great to add a input at bottom of a page (an input in CMS) for "Last points of contact". I feel like it'll be helpful for people with specific questions (instead of feeling lost and asking a whole channel).
![image](https://user-images.githubusercontent.com/8549171/52299302-0dad5b00-2953-11e9-881b-b83b4df9e64d.png)

- [x] Currently looks like the selected nav-bar item is being highlighted with an en dash, should be highlighted with an em dash (en) – (em) — ; slightly longer. 

- [x] Would it be possible to reduce the vertical space between these headings, and where the body copy starts? Please reduce by 10px.
![image](https://user-images.githubusercontent.com/8549171/52299958-bd36fd00-2954-11e9-8b81-aadb98525586.png)

- [x] For easier legibility, please make the body copy color `black60`
![image](https://user-images.githubusercontent.com/8549171/52300039-e8215100-2954-11e9-861a-9d101f25cff7.png)

- [x] Pls add 2px rounded corners on WIP tags

- [x] Pls adjust tag colors for WIP, and add a tag for TK ("to come", pre-build)
![image](https://user-images.githubusercontent.com/8549171/52300695-895cd700-2956-11e9-8147-a749340e325c.png)
WIP colors — background = `purple5`, type = `purple100`
TK colors — background = `black5`, type = `black60`

**Content Requests**

- [x] Under "Home", might be nice to have "Component Checklist" included there as well, so we can have a page that discusses what we care about when building components (it's included in the GH issue template). Will also be good to include our standards on Accessibility and Performance. Again, this is probably just a content thing that we can do, but just making a note!

- [x] Also "Home", would be great to add this "Terminology" to "Process"?
**Token**   Should primarily be a value, functionally agnostic
**Element**   Composition of various tokens. Specific function, content agnostic.
**Component**   Composition of various elements, may serve specific functionality that applies to a variety of content use cases. 
**Utility**   Specific function, is either not visible or exists temporarily.

- [ ] Would it be possible to display the actual type sizes for the type sizes, in parenthesis? Maybe something we (design) can just do via CMS.

 

Thank you !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by nicoleyeo** [comment]
@damassi this is ready for you whenever you are ready. 🙂

**Comment by damassi** [comment]
> only 1 dropdown set should be allowed to be open at a time

I really went back and forth on this! But I think I agree. 

Thanks for the feedback @nicoleyeo 👍 not so bad! Will get to it in a bit.

**Comment by damassi** [comment]
Ok addressed all feedback! 

I have the `Component Checklist` ask hidden behind a `showInNav: false` flag since there's no solid content yet, but the page is there and ya'll can toggle it on when ready.
