### ISSUE TITLE
[UPDATE] Elements / Dialogs / Modal

### ISSUE THREAD

**Issue by nicoleyeo** [artsy/palette#301]
Currently, the same "reusable" modal exists in 3 places and is not yet merged into Palette. 

[Artwork Page] Artwork Classification
[Artist Page] Artist Insights
[ArtistArtworkResults] Somewhere...in code

Purchase Team will need to reuse the same component again for Price Summaries, so I'm recommending making the time to transfer/formalize the modal component in Palette. 

Original zeplin spec: https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5c75ad115c1db5628cc03c2a

Jira ticket:
https://artsyproduct.atlassian.net/browse/PURCHASE-1019

**Comment by xtina-starr** [comment]
@nicoleyeo do these designs take in account modals that have images? The modal component in reaction supports modals with images. An example of a use case: https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5d080be2a33a5e15dece2e24
