### ISSUE TITLE
[NEW] Element / DataVisualization / DonutChart

### ISSUE THREAD

**Issue by owendodd** [artsy/palette#358]
### Zeplin link

zpl://screen?sid=5c9e845cca007d05b8b061ee&pid=5acd19ff49a1429169c3128b

### Product team

Galleries

### Design lead

@owendodd 

### Additional info
The one strange thing about this new component is that we need to use a few new shades of gray that fall outside of our existing color palette. I'd suggest hardcoding these as this usage is hyper specific to this component and I don't see those colors being necessary anywhere else. Happy to discuss further though

---

#### For Elements

_*Buttons, links, loaders, inputs, dropdowns, etc*_

- [ ] Is it using up-to-date tokens from above?

- [ ] Have all states been captured? (hover, selected, disabled, focused, normal, thinking, errors)

- [ ] Have all transitions/animations been defined?

- [ ] Is it useable? (Considering touch targets, screen sizes)

- [ ] Is it consistent with the rest of the visual system? (Corner radius, stroke weight, form, shadow, opacity, etc)

- [ ] Does it meet accessibility standards? (is it keyboard navigable, does it have required accessibility markup)

- [ ] Does it render and function properly in Artsy supported browsers?

#### Accessibility

- [ ] Do all images and multimedia have `alt` or `title` tags?

- [ ] Are semantic elements used appropriately (`nav`, `button`, etc)?

- [ ] Are new components keyboard-navigable?

- [ ] Are hover interactions available by other means?

- [ ] Are `aria-` attributes included where appropriate?

- [ ] Has a Chrome Devtools [accessibility audit](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#audits) been performed?

#### Compatibility

Has the new component been reviewed in [Browserstack](https://live.browserstack.com/dashboard):

- [ ] Desktop Chrome

- [ ] Desktop Edge

- [ ] Desktop Safari

- [ ] Desktop Firefox

- [ ] Android

- [ ] iOS

**Comment by damassi** [comment]
Before development on this begins we should have a larger discussion between design / engineering about where charting is expected to go at Artsy, and whether a formal charting library may be more maintainable over the long term than solutions that we roll in house. // cc @ds300

**Comment by owendodd** [comment]
@damassi Agreed, I'm definitely supportive of us using some sort of library.

**Comment by damassi** [comment]
Here are some non-exhaustive options: 
- https://uber.github.io/react-vis/
- https://formidable.com/open-source/victory/gallery/
- http://recharts.org/en-US/examples
- http://reactcommunity.org/react-chartjs/index.html
- https://chartkick.com/react
- https://react-google-charts.com/

**Comment by ds300** [comment]
It makes sense to use a charting library when the chart you're building would be easier to build with a charting library.

This DonutChart would probably be significantly easier to build and maintain with a charting library that supports donut charts out of the box and can be styled easily.

The BarChart is an example of a chart that would counterintuitively be harder to build and maintain using a charting library IMO. Unless you can find one that does everything we need out of the box and is easy to style.

IME charting libraries can be really hard to bend to custom requirements. They have opinions or just unthoughtful APIs that can make it difficult to do custom stuff. Things like adding labels or tooltips with tricksy positioning, styling certain elements (like putting margins between pies in a pie chart, or making one of the pies bigger to emphasize it), or making any custom interactive/dynamic features.

Charting libraries become most valuable when you can be flexible with your designs to suit what the charting library itself is designed for. That's fine for backoffice or B2B software (which is what I've done mostly in the past) but doesn't feel like a good compromise for Artsy to be making.

**Comment by damassi** [comment]
At my last company we used Victory extensively and had some pretty cool and flexible charts, built with minimal effort, which involved all kinds of custom styling and interactive behavior. (Not suggesting we use Victory, however.) It would be worth seeing what's possible in a spike, and exploring the options available to us in 2019. There's not _necessarily_ a trade-off.

**Comment by ds300** [comment]
Victory looks nice. Seems to be made of small pluggable SVG components rather than the monolithic kind of thing my reservations were base on (e.g. recharts).
