### ISSUE TITLE
[Update] Elements / Inputs / SelectSmall

### ISSUE THREAD

**Issue by owendodd** [artsy/palette#482]
## Component Name
Select Small

### Zeplin link

zpl://screen?sid=5cf04497b9a2d41db6d26ad7&pid=5acd19ff49a1429169c3128b

### Product team

Galleries (or TBD)

### Design lead

@owendodd 

### Additional info

Adds custom dropdown implementation to `SelectSmall` element.

---

#### For Elements

_*Buttons, links, loaders, inputs, dropdowns, etc*_

- [x] Is it using up-to-date tokens from above?

- [x] Have all states been captured? (hover, selected, disabled, focused, normal, thinking, errors)

- [x] Have all transitions/animations been defined?

- [x] Is it useable? (Considering touch targets, screen sizes)

- [x] Is it consistent with the rest of the visual system? (Corner radius, stroke weight, form, shadow, opacity, etc)

- [x] Does it meet accessibility standards? (is it keyboard navigable, does it have required accessibility markup)

- [x] Does it render and function properly in Artsy supported browsers?

#### Accessibility

- [ ] Do all images and multimedia have `alt` or `title` tags?

- [ ] Are semantic elements used appropriately (`nav`, `button`, etc)?

- [ ] Are new components keyboard-navigable?

- [ ] Are hover interactions available by other means?

- [ ] Are `aria-` attributes included where appropriate?

- [ ] Has a Chrome Devtools [accessibility audit](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#audits) been performed?

#### Compatibility

Has the new component been reviewed in [Browserstack](https://live.browserstack.com/dashboard):

- [ ] Desktop Chrome

- [ ] Desktop Edge

- [ ] Desktop Safari

- [ ] Desktop Firefox

- [ ] Android

- [ ] iOS

**Comment by samchieng** [comment]
@oxaudo hello! can you confirm this was built?

**Comment by oxaudo** [comment]
Hi hi @samchieng - the SelectSmall is implemented here: https://palette.artsy.net/elements/inputs/selectsmall/

Not sure 100% if that can be counted as a final version. This select is based on native browser `<select>` so it might look slightly different depending on a browser. However it was good enough for what we needed it - so that is what it is for now.
