### ISSUE TITLE
Firefox updates to palette

### ISSUE THREAD

**Issue by samchieng** [artsy/palette#535]
Noticed a few issues with palette components on Firefox. These are the ones @erikdstock noticed but we might want to go through an audit and see if there's anything else that's Firefox related.

**Add font smoothing styles to palette typography for Firefox**

It appears that firefox isn’t applying font smoothing styles to some palette components. Here you can see it especially on the title and button text in this modal I’m working on. (Firefox  |  Chrome)

![image](https://user-images.githubusercontent.com/6038013/60995854-709b8780-a321-11e9-8c4d-449f2045b239.png)

**Checkbox style shows two checkboxes on Firefox**

![2019-07-12 12 36 41](https://user-images.githubusercontent.com/6038013/61492007-7bd46000-a97e-11e9-9453-c6276db4de04.gif)

**Can't agree to COS on Firefox Mobile**

![2019-07-18 16 08 25](https://user-images.githubusercontent.com/6038013/61492001-74ad5200-a97e-11e9-8ee7-ca1b8b264840.gif)

**Comment by erikdstock** [comment]
Just realized that the last example[ Can't agree to COS on Firefox Mobile ] is from old styles, not palette!

**Comment by samchieng** [comment]
Look into more cross-browser testing

**Comment by erikdstock** [comment]
Just realized that the first example (authentication modal) is actually a more custom checkbox in reaction, so this may be entirely unrelated to palette!
[slack thread](https://artsy.slack.com/archives/C2MEQ2HA6/p1564687886075400)

**Comment by zephraph** [comment]
Yep. Neither of these components are from Palette. There's definitely still some weirdness that needs to be sorted out in those relevant apps, but there's nothing to do in Palette for this issue.
