### ISSUE TITLE
Accessibility Rules

### ISSUE THREAD

**Issue by samchieng** [artsy/palette#585]
Currently Artsy's design system doesn't pass for color contrast, tiny fonts ('buy now' tags), alt tags, etc. We should:
1. Audit our existing design system for accessibility
2. Create clear guidelines for accessibility to include in Palette

**Comment by anandaroop** [comment]
Not sure if we are still using [this template](https://github.com/artsy/palette/issues/new?template=component-spec.md) to start the workflow for components, but we had [previously created](https://github.com/artsy/palette/pull/123) a small checklist of impactful accessibility items for engineers to consider:

> - [ ] Do all images and multimedia have `alt` or `title` tags?
> 
> - [ ] Are semantic elements used appropriately (`nav`, `button`, etc)?
> 
> - [ ] Are new components keyboard-navigable?
> 
> - [ ] Are hover interactions available by other means?
> 
> - [ ] Are `aria-` attributes included where appropriate?
> 
> - [ ] Has a Chrome Devtools [accessibility audit](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#audits) been performed?

Sounds like we may need to tweak this based on recent finds, but this would be solid start for any new component we build.

**Comment by samchieng** [comment]
@anandaroop good callout, I forgot about this checklist! Definitely agree we should keep this in our workflow, but I think this came out of also needing for Design to be accountable for accessibility early on as well.

**Comment by samchieng** [comment]
Moved to Jira
https://artsyproduct.atlassian.net/browse/DSG-7
