### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by briansw** [artsy/palette#82]
This design exists within the new iOS bid flow (cc @sweir27). We'll be using it in BNMO flow and all future dialog messaging.

Zeplin web: https://zpl.io/bevQWrP
Zeplin app: zpl://screen?sid=5b9a7bdaa2fa5551fff7c014&pid=5acd19ff49a1429169c3128b

**Comment by sweir27** [comment]
😐My bad. I did not make this as part of palette, and actually made our current reaction modals generic to support.

Does this include the entire modal or just the internal dialog?

**Comment by zephraph** [comment]
Closing this in favor of #301
