### ISSUE TITLE
[RFC] Sidebar Organization

### ISSUE THREAD

**Issue by owendodd** [artsy/palette#83]
This is an initial proposal of how Palette could be organized. I moved consolidate existing components that have already been added to Palette along with some that live in Reaction and have tried to outline where new components would go.

I'd like to get feedback on this general structure. Along with thoughts on whether there should be any further additions / subtractions to this outline.

I'm currently using this framework for classifying tokens/elements/components.

**Token:** Should primarily be a value, functionally agnostic
**Element:** Composition of various tokens. Specific function, content agnostic.
**Utility:** Specific function, is either not visible or exists temporarily. 
**Component:** Content specific UI. 

Here I am suggesting that a limited number of components should be included in Palette as they are a core part of our site and are regularly used across projects. I would imagine that this list of components would stay fairly fixed. 

---

**Home**
- About
- Change-log

---

**Tokens**
- Color
- Typography
- Spacing
- Grid
- Icons

---

**Elements**
- Images
  - Avatar
  - Image
  - ImageCarousel
  - LightBox
- Layout
  - BorderBox
  - Box
  - Flex
  - StackableBorderBox
  - Separator
  - Join
  - Overflow
  - ReadMore
- Buttons
  - Buttons
  - Text links
- Forms
  - Input
  - QuickInput
  - Radio
  - GroupRadio
  - Checkbox
  - Dropdown
  - MiniDropdown
  - Slider
- Dialogs
  - Banner
  - Modal
  - Alert
  - Message
  - Confirmation
  - Tooltip
  - PopOver
- Navigation
  - Tabs
  - Pagination
- Animation
- Loaders
  - Spinner

---

**Components**
- Header
- Footer
- Bricks
  - ArtistBrick
  - GalleryBrick
  - ShowBrick
  - ArticleBrick
  - ArtworkBrick

**Comment by damassi** [comment]
One edit I would suggest is putting `Flex` at the same level as `Box` (they're definitely close friends around the codebase), and renaming `Box` category header to `Layout` and moving all layout related things inside of it (including `Join`). 

Another suggestion is that `ReadMore` be moved out of utilities since it's a component in practice, and has very specific requirements. (Utilities is somewhat hard to define within a component context.)

**Comment by owendodd** [comment]
@damassi Cool, that all makes sense. Incorporated those changes and collapsed "Utilities"

**Comment by damassi** [comment]
`Layout` folder looks great 👍 Thinking `ReadMore` can be moved under the catch-all `Components` folder? It's not used for laying out a page, but is rather a text truncation component.

**Comment by owendodd** [comment]
@nicoleyeo Sorry for delay, incorporated your notes for 2 and 3. Re: header, I meant site-wide nav! 

@damassi Hmmm, based on the framework I was working with (elements being non-content specific), I feel like `ReadMore` does fit in that bucket better. And in my mind, limiting content length is a `Layout` decision more than anything else. I could put in a separate `Elements / Truncation` section though if that feels better to you

**Comment by damassi** [comment]
No its all good! Under `Layout` seems fine for now. If anyone finds it to be confusing we can revisit.

**Comment by nicoleyeo** [comment]
@owendodd fyi — in DesSysSync today, we discussed that this was good to go 👍. I'm going to add this to "In Progress", do we have plans for who will implement this new structure? (Does that need to be assigned?)

**Comment by jeffreytr** [comment]
Hope I'm not too late here! I had a few comments, to make sure we're capturing everything possible...

-In the 'Home' section, did we consider a general principles or foundations section? Shopify does a good job of this (https://polaris.shopify.com/guides/principles).. Could be built out later down the road.. 
- Have we considered other names than "tokens" ... perhaps "Foundations" or "Identity" or "Design Foundations"
- Buttons might also want to include text links / in-line links? (what do we consider the follow link style?)
- Is "Navigation" the same thing as "header/ footer" ?? If so, it's duplicated in both elements and components. IMO, it should be a component since it's a combination of elements, not an element itself.
- Might want to include modals in components

**Comment by owendodd** [comment]
@jeffreytr Sorry for the late reply!

Re: adding a general principles / approach section, definitely agree that we should do this. I think there will need to be a bit more work on our end to figure out the content here. Adding to agenda for next weeks meeting. 

- We considered a few different naming options for 'Tokens' and landed there as it felt like it implied that it is a value based variable more than anything else. This is following the model that Salesforce uses in their system. Happy to discuss further in person though if you feel strongly about it! 
- +1 to including text links under buttons, will update
- "Navigation" under elements is referring to navigational elements (not sitewide nav), so things like our pagination UI or the tab UI, both of which are used in a number of different contexts. Header / footer refer to the actual sitewide navigation. I'm realizing the terminology here is probably confusing, will try to come up withe something a little more clear. 
- Modals are sitting under elements now as they are content agnostic, and can be used in a variety of ways. That being said, I think something like the login modal could fall under components, as it is fairly universal and serves a single purpose.

**Comment by owendodd** [comment]
Resolution: We will adopt the proposed architecture as a baseline structure for current palette components and future additions.

**Comment by nicoleyeo** [comment]
@owendodd might be good to keep this as rules/source of truth and guidelines for the component organization overall? Cleaning up notes from last meeting, and wanted to note the following:

Existence of **React** and **React Native** components should be explicit on component pages. Viewers should be able to know if a component is built in both, or only in 1 of the languages. (ie: Picker)

**Comment by nicoleyeo** [comment]
@owendodd was just chatting with jeffrey about some process stuff, maybe lets change this issue title to "Master" or something, so we remember to reference?
